/* Wortgleiche KI-Anweisungen und Partiturformat aus MiniComposer V0.4.24.
 * Referenz unveränderlich lassen. */
export const CLASSIC_VERSION='0.4.24';
export const CLASSIC_TECHNICAL_CONTRACT="TECHNISCHE AUSGABEANFORDERUNG – KEINE MUSIKALISCHEN ZUSATZREGELN:\nAntworte ausschließlich mit validem JSON, ohne Markdown und ohne Text außerhalb des JSON.\nDie Partitur steht entweder direkt im Wurzelobjekt oder im Feld \"score\".\nPartiturformat:\n{\n  \"title\": \"optional\",\n  \"bpm\": Zahl,\n  \"timeSignature\": [Zaehler, Nenner],\n  \"tracks\": [\n    {\n      \"name\": \"Instrument\",\n      \"program\": 0-127,\n      \"channel\": 0-15,\n      \"notes\": [[StartBeat, DauerInBeats, MIDIPitch, Velocity], ...]\n    }\n  ]\n}\nWeitere Textfelder, die der Benutzer in seinem Auftrag ausdrücklich verlangt, dürfen zusätzlich im JSON stehen.\nStartBeat und DauerInBeats dürfen Dezimalzahlen sein. MIDI-Pitch 0-127, Velocity 1-127.\nDas technische Format macht keinerlei Vorgaben zu Stil, Harmonik, Melodik, Rhythmik, Form, Artikulation oder musikalischer Qualität.";
const DRAFT="Komponiere das verlangte Stück musikalisch frei und eigenständig. Konzentriere dich ausschließlich auf musikalische Gestalt, Verlauf, Stimmen, Rhythmus, Harmonik, Artikulation und Charakter. Denke noch NICHT an MIDI-Codierung, QN-Werte, CS-Zeilen oder ein technisches Ausgabeformat. Schreibe einen vollständigen, konkret ausnotierbaren musikalischen Entwurf, aus dem anschließend eine andere technische Instanz die MIDI-Daten erzeugen kann. Gib in der ersten Zeile lediglich einen kurzen passenden Werktitel als „Titel: …“ an; dies soll die musikalische Gestaltung nicht einschränken. Mache keine Erläuterung über deine Arbeitsweise.\n\nAUFTRAG:\n";
const TRANSLATE="Du bist jetzt ausschließlich Notations- und MIDI-Übersetzer. Übertrage den folgenden bereits fertigen musikalischen Entwurf so vollständig und werkgetreu wie möglich in das nachfolgend geforderte technische Partiturformat. Komponiere NICHT neu, vereinfache NICHT, regularisiere NICHT den Rhythmus und ersetze keine ungewöhnlichen musikalischen Entscheidungen durch Standards. Bewahre insbesondere rhythmische Vielfalt, Pausen, Stimmführung und Phrasierung des Entwurfs.\n\nURSPRÜNGLICHER AUFTRAG:\n";
const MIDDLE="\n\nFERTIGER MUSIKALISCHER ENTWURF:\n";
const SUFFIX="\n\n";
const IDEA="Analysiere die soeben entstandene Komposition und formuliere ihre Kompositionsidee knapp und musikalisch konkret. Beschreibe Charakter, formalen Verlauf, rhythmische und harmonische Grundidee sowie das Verhältnis der Stimmen bzw. Instrumente. Erfinde nichts und gib keine Bewertung ab. Antworte nur mit der Kompositionsidee als normalem Text.\n\nURSPRÜNGLICHER AUFTRAG:\n";
const IDEA_MIDDLE="\n\nMUSIKALISCHER ENTWURF:\n";
const IDEA_SUFFIX="\n\nTECHNISCHE PARTITUR:\n";
export const classicDraftPrompt=task=>DRAFT+String(task).trim();
export const classicTranslationPrompt=(task,draft)=>TRANSLATE+String(task).trim()+MIDDLE+draft+SUFFIX+CLASSIC_TECHNICAL_CONTRACT;
export const classicIdeaPrompt=(task,draft,translated)=>IDEA+String(task).trim()+IDEA_MIDDLE+draft+IDEA_SUFFIX+translated;
